using Shopfloor.Material.Application.Models.Buyers;
using Shopfloor.Material.Application.Models.MaterialRequests;
using Shopfloor.Material.Application.Models.PriceLists;
using Shopfloor.Material.Application.Models.Suppliers;

namespace Shopfloor.Material.Application.Definitions
{
    public static class FieldMaps
    {
        public static Dictionary<string, string> Buyer
        {
            get
            {
                return new Dictionary<string, string>
                {
                    { "A", nameof(BuyerImportExcelModel.Name) },
                    { "B", nameof(BuyerImportExcelModel.Code) },
                    { "C", nameof(BuyerImportExcelModel.ShortName) },
                    { "D", nameof(BuyerImportExcelModel.Address) },
                    { "E", nameof(BuyerImportExcelModel.Address2) },
                    { "F", nameof(BuyerImportExcelModel.Address3) },
                    { "G", nameof(BuyerImportExcelModel.BillAddress) },
                    { "H", nameof(BuyerImportExcelModel.ShipAddress) },
                    { "I", nameof(BuyerImportExcelModel.City) },
                    { "J", nameof(BuyerImportExcelModel.State) },
                    { "K", nameof(BuyerImportExcelModel.ZipCode) },
                    { "L", nameof(BuyerImportExcelModel.Country) },
                    { "M", nameof(BuyerImportExcelModel.Telephone) },
                    { "N", nameof(BuyerImportExcelModel.Currency) },
                    { "O", nameof(BuyerImportExcelModel.BuyerType) },
                    { "P", nameof(BuyerImportExcelModel.ContactFirstName) },
                    { "Q", nameof(BuyerImportExcelModel.ContactLastName) },
                    { "R", nameof(BuyerImportExcelModel.ContactEmail) },
                    { "S", nameof(BuyerImportExcelModel.BusinessSegment) },
                    { "T", nameof(BuyerImportExcelModel.ProductCategory) },
                    { "U", nameof(BuyerImportExcelModel.Tolearance) },
                    { "V", nameof(BuyerImportExcelModel.PaymentTerms) },
                    { "W", nameof(BuyerImportExcelModel.DeliveryTerms) },
                    { "X", nameof(BuyerImportExcelModel.ShipmentTerms) },
                    { "Y", nameof(BuyerImportExcelModel.FinalDestination) },
                    { "Z", nameof(BuyerImportExcelModel.CountryOfFinalDestination) },
                    { "AA", nameof(BuyerImportExcelModel.PortofDischarge) },
                    { "AB", nameof(BuyerImportExcelModel.GroupNameCode) },
                    { "AC", nameof(BuyerImportExcelModel.Category) },
                    { "AD", nameof(BuyerImportExcelModel.PAN) },
                    { "AE", nameof(BuyerImportExcelModel.TIN) },
                    { "AF", nameof(BuyerImportExcelModel.AccountGroup) },
                    { "AG", nameof(BuyerImportExcelModel.Market) },
                    { "AH", nameof(BuyerImportExcelModel.CustomHouse) },
                    { "AI", nameof(BuyerImportExcelModel.VATNumber) },
                    { "AJ", nameof(BuyerImportExcelModel.BankAccountNumber) },
                    { "AK", nameof(BuyerImportExcelModel.BankAddress) },
                    { "AL", nameof(BuyerImportExcelModel.SwiftCode) },
                    { "AM", nameof(BuyerImportExcelModel.MaximumOutAmount) }
                };
            }
        }

        public static Dictionary<string, string> PriceList =>
            new()
            {
                { "A", nameof(PriceListImportExcelModel.SupplierCode) },
                { "B", nameof(PriceListImportExcelModel.ArticleCode) },
                { "C", nameof(PriceListImportExcelModel.ColorCode) },
                { "D", nameof(PriceListImportExcelModel.ColorName) },
                { "E", nameof(PriceListImportExcelModel.SizeCode) },
                { "F", nameof(PriceListImportExcelModel.DeliveryTerm) },
                { "G", nameof(PriceListImportExcelModel.Price) },
                { "H", nameof(PriceListImportExcelModel.Currency) },
                { "I", nameof(PriceListImportExcelModel.ValidFrom) },
                { "J", nameof(PriceListImportExcelModel.ValidTo) },
                { "K", nameof(PriceListImportExcelModel.Uom) },
            };

        public static Dictionary<string, string> Supplier =>
             new()
             {
                 { "A", nameof(SupplierImportExcelModel.CompanyId) },
                 { "B", nameof(SupplierImportExcelModel.Name) },
                 { "C", nameof(SupplierImportExcelModel.ShortName) },
                 { "D", nameof(SupplierImportExcelModel.Address) },
                 { "E", nameof(SupplierImportExcelModel.BillAddress) },
                 { "F", nameof(SupplierImportExcelModel.ShipAddress) },
                 { "G", nameof(SupplierImportExcelModel.City) },
                 { "H", nameof(SupplierImportExcelModel.State) },
                 { "I", nameof(SupplierImportExcelModel.ZipCode) },
                 { "J", nameof(SupplierImportExcelModel.CountryName) },
                 { "K", nameof(SupplierImportExcelModel.Telephone) },
                 { "L", nameof(SupplierImportExcelModel.CurrencyName) },
                 { "M", nameof(SupplierImportExcelModel.ContactFirstName) },
                 { "N", nameof(SupplierImportExcelModel.ContactLastName) },
                 { "O", nameof(SupplierImportExcelModel.Email) },
                 { "P", nameof(SupplierImportExcelModel.BusinessSegment) },
                 { "Q", nameof(SupplierImportExcelModel.ProductCategory) },
                 { "R", nameof(SupplierImportExcelModel.Tolearancen) },
                 { "S", nameof(SupplierImportExcelModel.PaymentTerms) },
                 { "T", nameof(SupplierImportExcelModel.DeliveryTerms) },
                 { "U", nameof(SupplierImportExcelModel.ShipmentTerms) },
                 { "V", nameof(SupplierImportExcelModel.CountryOfOrigin) },
                 { "W", nameof(SupplierImportExcelModel.PortOfLoading) },
                 { "X", nameof(SupplierImportExcelModel.GroupName) },
                 { "Y", nameof(SupplierImportExcelModel.CategoryName) },
                 { "Z", nameof(SupplierImportExcelModel.Pan) },
                 { "AA", nameof(SupplierImportExcelModel.Tin) },
                 { "AB", nameof(SupplierImportExcelModel.AccountGroupName) },
                 { "AC", nameof(SupplierImportExcelModel.CustomHouse) },
                 { "AD", nameof(SupplierImportExcelModel.VATNumber) },
                 { "AE", nameof(SupplierImportExcelModel.SupplierTypeName) },
                 { "AF", nameof(SupplierImportExcelModel.BankAccountNumber) },
                 { "AG", nameof(SupplierImportExcelModel.BankAddressDetails) },
                 { "AH", nameof(SupplierImportExcelModel.SwiftCode) },
                 { "AI", nameof(SupplierImportExcelModel.MaximumOutAmount) }
             };

        public static Dictionary<string, string> TrimsRequest =>
            new()
            {
                { "A", nameof(MaterialImportExcelModel.ProductGroupCode) },
                { "B", nameof(MaterialImportExcelModel.ProductSubCatCode) },
                { "C", nameof(MaterialImportExcelModel.ArticleCode) },
                { "D", nameof(MaterialImportExcelModel.ArticleName) },
                { "E", nameof(MaterialImportExcelModel.ArticleDesc) },
                { "F", nameof(MaterialImportExcelModel.FabricAndMaterial) },
                { "G", nameof(MaterialImportExcelModel.ColorTypeCode) },
                { "H", nameof(MaterialImportExcelModel.ColorGroupCode) },
                { "I", nameof(MaterialImportExcelModel.SizeGroupCode) },
                { "J", nameof(MaterialImportExcelModel.SeasonCode) },
                { "K", nameof(MaterialImportExcelModel.DivisionCode) },
                { "L", nameof(MaterialImportExcelModel.UomCode) },
                { "M", nameof(MaterialImportExcelModel.StoringUomCode) },
                { "N", nameof(MaterialImportExcelModel.OurContactCode) },
                { "O", nameof(MaterialImportExcelModel.BuyerCode) },
                { "P", nameof(MaterialImportExcelModel.BuyerRef) },
                { "Q", nameof(MaterialImportExcelModel.SupplierName) },
                { "R", nameof(MaterialImportExcelModel.SupplierRef) },
                { "S", nameof(MaterialImportExcelModel.BuyingPrice) },
                { "T", nameof(MaterialImportExcelModel.BuyingCurrencyCode) },
                { "U", nameof(MaterialImportExcelModel.PricePerCode) },
                { "V", nameof(MaterialImportExcelModel.MinimumQty) },
                { "W", nameof(MaterialImportExcelModel.MaximumQty) },
                { "X", nameof(MaterialImportExcelModel.MinimumOrderQty) },
                { "Y", nameof(MaterialImportExcelModel.RequirementMultiple) },
                { "Z", nameof(MaterialImportExcelModel.ReorderLevel) },
                { "AA", nameof(MaterialImportExcelModel.OrderQtyMultiple) },
                { "AB", nameof(MaterialImportExcelModel.Remarks) },
                { "AC", nameof(MaterialImportExcelModel.CatalogPath) },
                { "AD", nameof(MaterialImportExcelModel.MaterialTypeCode) },
                { "AE", nameof(MaterialImportExcelModel.ConsUomCode) },
                { "AF", nameof(MaterialImportExcelModel.HSNCode) },
                { "AG", nameof(MaterialImportExcelModel.ArticleNameChinese) },
                { "AH", nameof(MaterialImportExcelModel.ButtonType) },
                { "AI", nameof(MaterialImportExcelModel.ButtonHole) },
                { "AJ", nameof(MaterialImportExcelModel.ElasticType) },
                { "AK", nameof(MaterialImportExcelModel.RivetType) },
                { "AL", nameof(MaterialImportExcelModel.ZipperType) },
                { "AM", nameof(MaterialImportExcelModel.Layer) },
                { "AN", nameof(MaterialImportExcelModel.Brand) },
                { "AO", nameof(MaterialImportExcelModel.Tex) },
            };

        public static Dictionary<string, string> FabricRequest =>
            new()
            {
                { "A", nameof(MaterialImportExcelModel.ProductGroupCode) },
                { "B", nameof(MaterialImportExcelModel.ProductSubCatCode) },
                { "C", nameof(MaterialImportExcelModel.ArticleCode) },
                { "D", nameof(MaterialImportExcelModel.ArticleName) },
                { "E", nameof(MaterialImportExcelModel.ArticleDesc) },
                { "F", nameof(MaterialImportExcelModel.ColorTypeCode) },
                { "G", nameof(MaterialImportExcelModel.ColorGroupCode) },
                { "H", nameof(MaterialImportExcelModel.SizeGroupCode) },
                { "I", nameof(MaterialImportExcelModel.SeasonCode) },
                { "J", nameof(MaterialImportExcelModel.DivisionCode) },
                { "K", nameof(MaterialImportExcelModel.UomCode) },
                { "L", nameof(MaterialImportExcelModel.StoringUomCode) },
                { "M", nameof(MaterialImportExcelModel.BuyerRef) },
                { "N", nameof(MaterialImportExcelModel.SupplierName) },
                { "O", nameof(MaterialImportExcelModel.SupplierRef) },
                { "P", nameof(MaterialImportExcelModel.BuyingPrice) },
                { "Q", nameof(MaterialImportExcelModel.BuyingCurrencyCode) },
                { "R", nameof(MaterialImportExcelModel.CountCode) },
                { "S", nameof(MaterialImportExcelModel.ConstructionCode) },
                { "T", nameof(MaterialImportExcelModel.ContentName) },
                { "U", nameof(MaterialImportExcelModel.PricePerCode) },
                { "V", nameof(MaterialImportExcelModel.DesignAndPattern) },
                { "W", nameof(MaterialImportExcelModel.Weight) },
                { "X", nameof(MaterialImportExcelModel.MinimumQty) },
                { "Y", nameof(MaterialImportExcelModel.MaximumQty) },
                { "Z", nameof(MaterialImportExcelModel.MinimumOrderQty) },
                { "AA", nameof(MaterialImportExcelModel.RequirementMultiple) },
                { "AB", nameof(MaterialImportExcelModel.ReorderLevel) },
                { "AC", nameof(MaterialImportExcelModel.OrderQtyMultiple) },
                { "AD", nameof(MaterialImportExcelModel.PerSizeConsCode) },
                { "AE", nameof(MaterialImportExcelModel.CatalogPath) },
                { "AF", nameof(MaterialImportExcelModel.MaterialTypeCode) },
                { "AG", nameof(MaterialImportExcelModel.ConsUomCode) },
                { "AH", nameof(MaterialImportExcelModel.FabricComposition) },
                { "AI", nameof(MaterialImportExcelModel.HSNCode) },
                { "AJ", nameof(MaterialImportExcelModel.ArticleNameChinese) },
                { "AK", nameof(MaterialImportExcelModel.TCFNO) },
                { "AL", nameof(MaterialImportExcelModel.GSM) },
                { "AM", nameof(MaterialImportExcelModel.NoOfEnds) },
                { "AN", nameof(MaterialImportExcelModel.SpinningMethod) },
                { "AO", nameof(MaterialImportExcelModel.Certificate) },
                { "AP", nameof(MaterialImportExcelModel.Gauge) },
                { "AQ", nameof(MaterialImportExcelModel.StitchLength) },
                { "AR", nameof(MaterialImportExcelModel.YarnComposition) },
                { "AS", nameof(MaterialImportExcelModel.CutWidth) },
                { "AT", nameof(MaterialImportExcelModel.Structure) },
                { "AU", nameof(MaterialImportExcelModel.HSCode) }
            };

        public static Dictionary<string, string> YarnsRequest =>
           new()
           {
                { "A", nameof(MaterialImportExcelModel.ProductGroupCode) },
                { "B", nameof(MaterialImportExcelModel.ProductSubCatCode) },
                { "C", nameof(MaterialImportExcelModel.ArticleCode) },
                { "D", nameof(MaterialImportExcelModel.ArticleName) },
                { "E", nameof(MaterialImportExcelModel.ArticleDesc) },
                { "F", nameof(MaterialImportExcelModel.ColorTypeCode) },
                { "G", nameof(MaterialImportExcelModel.ColorGroupCode) },
                { "H", nameof(MaterialImportExcelModel.SizeGroupCode) },
                { "I", nameof(MaterialImportExcelModel.SeasonCode) },
                { "J", nameof(MaterialImportExcelModel.DivisionCode) },
                { "K", nameof(MaterialImportExcelModel.UomCode) },
                { "L", nameof(MaterialImportExcelModel.StoringUomCode) },
                { "M", nameof(MaterialImportExcelModel.OurContactCode) },
                { "N", nameof(MaterialImportExcelModel.BuyerRef) },
                { "O", nameof(MaterialImportExcelModel.SupplierName) },
                { "P", nameof(MaterialImportExcelModel.SupplierRef) },
                { "Q", nameof(MaterialImportExcelModel.BuyingPrice) },
                { "R", nameof(MaterialImportExcelModel.BuyingCurrencyCode) },
                { "S", nameof(MaterialImportExcelModel.CountCode) },
                { "T", nameof(MaterialImportExcelModel.ConstructionCode) },
                { "U", nameof(MaterialImportExcelModel.ContentName) },
                { "V", nameof(MaterialImportExcelModel.PricePerCode) },
                { "W", nameof(MaterialImportExcelModel.DesignAndPattern) },
                { "X", nameof(MaterialImportExcelModel.MinimumOrder) },
                { "Y", nameof(MaterialImportExcelModel.MinimumQty) },
                { "Z", nameof(MaterialImportExcelModel.MaximumQty) },
                { "AA", nameof(MaterialImportExcelModel.MinimumOrderQty) },
                { "AB", nameof(MaterialImportExcelModel.RequirementMultiple) },
                { "AC", nameof(MaterialImportExcelModel.ReorderLevel) },
                { "AD", nameof(MaterialImportExcelModel.OrderQtyMultiple) },
                { "AE", nameof(MaterialImportExcelModel.PerSizeConsCode) },
                { "AF", nameof(MaterialImportExcelModel.CatalogPath) },
                { "AG", nameof(MaterialImportExcelModel.MaterialTypeCode) },
                { "AH", nameof(MaterialImportExcelModel.ConsUomCode) },
                { "AI", nameof(MaterialImportExcelModel.InternalPrice) },
                { "AJ", nameof(MaterialImportExcelModel.Finish) },
                { "AK", nameof(MaterialImportExcelModel.HSNCode) },
                { "AL", nameof(MaterialImportExcelModel.HTSCode) },
                { "AM", nameof(MaterialImportExcelModel.SpinningMethod) },
                { "AN", nameof(MaterialImportExcelModel.CountType) },
                { "AO", nameof(MaterialImportExcelModel.Certificate) },
                { "AP", nameof(MaterialImportExcelModel.SpinningProcess) },
                { "AQ", nameof(MaterialImportExcelModel.Pattern) },
                { "AR", nameof(MaterialImportExcelModel.Twist) }
           };

        public static Dictionary<string, string> MiscRequest =>
           new()
           {
                { "A", nameof(MaterialImportExcelModel.ProductGroupCode) },
                { "B", nameof(MaterialImportExcelModel.ProductSubCatCode) },
                { "C", nameof(MaterialImportExcelModel.ArticleCode) },
                { "D", nameof(MaterialImportExcelModel.ArticleName) },
                { "E", nameof(MaterialImportExcelModel.ArticleDesc) },
                { "F", nameof(MaterialImportExcelModel.UomCode) },
                { "G", nameof(MaterialImportExcelModel.StoringUomCode) },
                { "H", nameof(MaterialImportExcelModel.BuyerCode) },
                { "I", nameof(MaterialImportExcelModel.BuyerRef) },
                { "J", nameof(MaterialImportExcelModel.SupplierName) },
                { "K", nameof(MaterialImportExcelModel.SupplierRef) },
                { "L", nameof(MaterialImportExcelModel.BuyingPrice) },
                { "M", nameof(MaterialImportExcelModel.BuyingCurrencyCode) },
                { "N", nameof(MaterialImportExcelModel.MinimumQty) },
                { "O", nameof(MaterialImportExcelModel.MaximumQty) },
                { "P", nameof(MaterialImportExcelModel.ReorderLevel) },
                { "Q", nameof(MaterialImportExcelModel.CatalogPath) },
                { "R", nameof(MaterialImportExcelModel.MaterialTypeCode) },
                { "S", nameof(MaterialImportExcelModel.MinimumOrderQty) },
                { "T", nameof(MaterialImportExcelModel.OrderQtyMultiple) }
           };
    }
}